#!/usr/bin/env python3
"""
Saturday GENUS//NS bulletin — public registry facts only.

Assembles (does not invent) a weekly letter from data/published.json
and sends it via Brevo to BREVO_NEWSLETTER_LIST_ID.

Never include: file paths, package zips, ISRCs, keys, emails, Ditto/Stripe/Coolify,
unpublished backlog, composer credits, internal hostnames.

Usage:
  python scripts/newsletter_weekly.py --dry-run
  python scripts/newsletter_weekly.py --send
"""

from __future__ import annotations

import argparse
import html
import json
import os
import sys
import urllib.error
import urllib.request
from datetime import datetime, timedelta, timezone
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
GENUSNS = SCRIPT_DIR.parent
DATA = Path(os.environ.get("GENUSNS_DATA_DIR") or (GENUSNS / "data")).resolve()
SITE = "https://genusns.com"
SENDER_EMAIL = os.environ.get("BREVO_FROM_EMAIL") or "genusns@genusns.com"
SENDER_NAME = os.environ.get("BREVO_FROM_NAME") or "GENUS//NS"
API_BASE = "https://api.brevo.com/v3"
AGENT_DISCLOSURE = (
    "This newsletter is auto-generated by the same software agents that prepare "
    "GENUS//NS tracks. No human wrote this letter."
)
LOG = DATA / "newsletter_log.jsonl"


def _load_dotenv(path: Path) -> None:
    if not path.is_file():
        return
    for line in path.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if not s or s.startswith("#") or "=" not in s:
            continue
        key, _, val = s.partition("=")
        key = key.strip()
        if key in os.environ:
            continue
        os.environ[key] = val.strip().strip('"').strip("'")


def _api_key() -> str:
    _load_dotenv(GENUSNS / ".env")
    key = (os.environ.get("BREVO_API_KEY") or "").strip()
    if not key:
        raise SystemExit("BREVO_API_KEY missing")
    return key


def _list_id() -> int:
    raw = (os.environ.get("BREVO_NEWSLETTER_LIST_ID") or "").strip()
    n = int(raw) if raw.isdigit() else 0
    if n <= 0:
        raise SystemExit("BREVO_NEWSLETTER_LIST_ID missing")
    return n


def _request(method: str, path: str, key: str, body: dict | None = None) -> dict | None:
    data = None
    headers = {
        "api-key": key,
        "Accept": "application/json",
        "User-Agent": "GenusNS-newsletter/1.0 (+https://genusns.com)",
    }
    if body is not None:
        data = json.dumps(body).encode("utf-8")
        headers["Content-Type"] = "application/json"
    req = urllib.request.Request(
        API_BASE + path, data=data, headers=headers, method=method
    )
    try:
        with urllib.request.urlopen(req, timeout=90) as resp:
            raw = resp.read()
            return json.loads(raw.decode("utf-8")) if raw else None
    except urllib.error.HTTPError as exc:
        err = exc.read().decode("utf-8", errors="replace")[:1200]
        raise RuntimeError(f"{method} {path} HTTP {exc.code}: {err}") from exc


def _parse_when(raw: str) -> datetime | None:
    try:
        return datetime.fromisoformat(raw.replace("Z", "+00:00")).astimezone(timezone.utc)
    except ValueError:
        return None


def _public_entries(since: datetime) -> list[dict]:
    pub = json.loads((DATA / "published.json").read_text(encoding="utf-8"))
    out = []
    for e in pub.get("entries") or []:
        sid = str(e.get("id") or "").upper()[:6]
        if not sid:
            continue
        when = _parse_when(str(e.get("publishedAt") or ""))
        if when is None or when < since:
            continue
        # Public genome hints only (site-visible), never paths
        edo = cycle = bpm = None
        meta_path = DATA / "READY_FOR_DITTO" / sid / "DITTO_METADATA.json"
        if meta_path.is_file():
            try:
                meta = json.loads(meta_path.read_text(encoding="utf-8"))
                g = meta.get("genus") or {}
                edo = g.get("edo")
                cycle = g.get("cycle")
                bpm = g.get("bpm")
            except Exception:
                pass
        out.append(
            {
                "id": sid,
                "date": when.strftime("%Y-%m-%d"),
                "url": f"{SITE}/g/{sid}",
                "edo": edo,
                "cycle": cycle,
                "bpm": bpm,
            }
        )
    out.sort(key=lambda x: x["date"])
    return out


def _week_key(now: datetime) -> str:
    iso = now.isocalendar()
    return f"{iso.year}-W{iso.week:02d}"


def _already_sent(week: str) -> bool:
    if not LOG.is_file():
        return False
    for line in LOG.read_text(encoding="utf-8").splitlines():
        try:
            row = json.loads(line)
        except json.JSONDecodeError:
            continue
        if row.get("week") == week and row.get("ok"):
            return True
    return False


def _log(row: dict) -> None:
    LOG.parent.mkdir(parents=True, exist_ok=True)
    with LOG.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(row, ensure_ascii=False) + "\n")


def assemble(now: datetime, entries: list[dict], total_public: int) -> tuple[str, str, str]:
    week = _week_key(now)
    subject = f"GENUS//NS week {week} — agent bulletin"
    start = (now - timedelta(days=7)).strftime("%Y-%m-%d")
    end = now.strftime("%Y-%m-%d")

    if entries:
        lines = [
            f"{len(entries)} species went public on the registry between {start} and {end} UTC.",
            "Each line is a listen page. Nothing else is included.",
            "",
        ]
        for e in entries:
            extra = []
            if e.get("edo"):
                extra.append(f"{e['edo']}-EDO")
            if e.get("cycle"):
                extra.append(f"cycle {e['cycle']}")
            if e.get("bpm"):
                extra.append(f"{e['bpm']} bpm")
            tail = f" ({', '.join(str(x) for x in extra)})" if extra else ""
            lines.append(f"- {e['id']} · {e['date']}{tail} · {e['url']}")
    else:
        lines = [
            f"No new species entered the public registry between {start} and {end} UTC.",
            "The catalogue is unchanged this week. Listen to what is already up.",
        ]

    text = "\n".join(
        [
            "GENUS//NS",
            AGENT_DISCLOSURE,
            "",
            *lines,
            "",
            f"Public catalogue size: {total_public} species.",
            f"Registry: {SITE}",
            "",
            AGENT_DISCLOSURE,
        ]
    )

    rows_html = ""
    if entries:
        items = []
        for e in entries:
            extra = []
            if e.get("edo"):
                extra.append(f"{html.escape(str(e['edo']))}-EDO")
            if e.get("cycle"):
                extra.append(f"cycle {html.escape(str(e['cycle']))}")
            if e.get("bpm"):
                extra.append(f"{html.escape(str(e['bpm']))} bpm")
            meta = f" · {' · '.join(extra)}" if extra else ""
            items.append(
                f"<tr><td style='padding:8px 0;border-bottom:1px solid #3a372f;'>"
                f"<a href='{html.escape(e['url'])}' style='color:#e8e4d8;text-decoration:none;'>"
                f"<span style='font-family:Consolas,monospace;color:#c45c32;'>{html.escape(e['id'])}</span>"
                f"</a> · {html.escape(e['date'])}{meta}</td></tr>"
            )
        rows_html = "<table role='presentation' width='100%'>" + "".join(items) + "</table>"
        lead = (
            f"{len(entries)} species went public on the registry between "
            f"{html.escape(start)} and {html.escape(end)} UTC."
        )
    else:
        lead = (
            f"No new species entered the public registry between "
            f"{html.escape(start)} and {html.escape(end)} UTC. "
            "The catalogue is unchanged this week."
        )

    disc = html.escape(AGENT_DISCLOSURE)
    html_body = f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;background:#11110f;color:#e8e4d8;font-family:Georgia,serif;">
<table role="presentation" width="100%"><tr><td align="center" style="padding:28px 16px;">
<table role="presentation" width="560" style="max-width:560px;width:100%;">
<tr><td style="font-family:Consolas,monospace;font-size:11px;letter-spacing:0.22em;color:#c45c32;">GENUS//NS · WEEK {html.escape(week)}</td></tr>
<tr><td style="padding:16px 0;border-top:1px solid #3a372f;border-bottom:1px solid #3a372f;font-family:Consolas,monospace;font-size:12px;line-height:1.55;color:#e0b59a;">{disc}</td></tr>
<tr><td style="padding-top:20px;font-size:16px;line-height:1.55;">{lead}</td></tr>
<tr><td style="padding-top:16px;">{rows_html}</td></tr>
<tr><td style="padding-top:18px;font-size:14px;color:#9a9588;">Public catalogue: {total_public} species.</td></tr>
<tr><td style="padding-top:16px;"><a href="{SITE}" style="font-family:Consolas,monospace;font-size:12px;letter-spacing:0.14em;color:#c45c32;">GENUSNS.COM</a></td></tr>
<tr><td style="padding-top:28px;font-family:Consolas,monospace;font-size:11px;line-height:1.5;color:#9a9588;">{disc}</td></tr>
</table></td></tr></table>
</body></html>"""
    return subject, text, html_body


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--send", action="store_true")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--force", action="store_true", help="ignore already-sent week marker")
    args = ap.parse_args()
    send = args.send or not args.dry_run
    if args.dry_run:
        send = False

    now = datetime.now(timezone.utc)
    week = _week_key(now)
    since = now - timedelta(days=7)
    pub_path = DATA / "published.json"
    if not pub_path.is_file():
        raise SystemExit(f"missing {pub_path}")
    pub = json.loads(pub_path.read_text(encoding="utf-8"))
    total = len(pub.get("entries") or [])
    entries = _public_entries(since)
    subject, text, html_body = assemble(now, entries, total)

    preview = DATA / "_newsletter_preview.html"
    preview.write_text(html_body, encoding="utf-8")
    print(f"week={week} species_this_week={len(entries)} total={total}")
    print(f"subject={subject}")
    print(f"preview={preview}")

    if not send:
        print("dry-run: not sent")
        return 0

    if _already_sent(week) and not args.force:
        print("already sent this ISO week; skip")
        return 0

    key = _api_key()
    list_id = _list_id()
    created = _request(
        "POST",
        "/emailCampaigns",
        key,
        {
            "name": f"GENUS//NS {week}",
            "subject": subject,
            "sender": {"name": SENDER_NAME, "email": SENDER_EMAIL},
            "type": "classic",
            "htmlContent": html_body,
            "recipients": {"listIds": [list_id]},
            "inlineImageActivation": False,
        },
    )
    assert isinstance(created, dict)
    cid = int(created["id"])
    _request("POST", f"/emailCampaigns/{cid}/sendNow", key, {})
    row = {
        "ok": True,
        "week": week,
        "campaignId": cid,
        "count": len(entries),
        "at": now.isoformat().replace("+00:00", "Z"),
    }
    _log(row)
    print(json.dumps(row))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc
