/** Public welcome dispatch — same letter for every new subscriber. No secrets. */

export const WELCOME_SUBJECT =
  "GENUS//NS — a letter from the agents (welcome)";

export const AGENT_DISCLOSURE =
  "This newsletter is auto-generated by the same software agents that prepare GENUS//NS tracks. No human wrote this letter.";

const SITE = "https://genusns.com";

export function welcomeText(): string {
  return [
    "GENUS//NS",
    "Rondanini Publishing Ltd t/a 0dB_Labs",
    "",
    AGENT_DISCLOSURE,
    "",
    "You asked to receive publication notices. This is the first letter. Every new subscriber gets this same one.",
    "",
    "WHAT THIS IS",
    "GENUS//NS is a public registry of invented musical species — music for genres that do not exist yet. Genus is the laboratory. GENUS//NS is the publication layer. Neural Syntax operates it. 0dB_Labs is the label.",
    "",
    "Each species has a short id (for example 288FBD), a genome (tuning, rhythm, form), a cover grown from that law, and a master you can listen to on the site.",
    "",
    "WHAT YOU WILL GET ON SATURDAYS",
    "Once a week the same agents assemble a short bulletin: which species went public, listen links, and nothing else. No internal tools, no unreleased work, no private correspondence.",
    "",
    `Listen and subscribe management: ${SITE}`,
    "Unsubscribe using the link at the bottom of this email.",
    "",
    AGENT_DISCLOSURE,
  ].join("\n");
}

export function welcomeHtml(): string {
  const d = AGENT_DISCLOSURE;
  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width"></head>
<body style="margin:0;padding:0;background:#11110f;color:#e8e4d8;font-family:Georgia,serif;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#11110f;">
    <tr><td align="center" style="padding:28px 16px;">
      <table role="presentation" width="560" cellpadding="0" cellspacing="0" style="max-width:560px;width:100%;">
        <tr><td style="font-family:Consolas,monospace;font-size:11px;letter-spacing:0.22em;color:#c45c32;">GENUS//NS</td></tr>
        <tr><td style="padding-top:6px;font-family:Consolas,monospace;font-size:10px;letter-spacing:0.12em;color:#9a9588;">RONDANINI PUBLISHING LTD T/A 0DB_LABS</td></tr>
        <tr><td style="padding:18px 0 8px;border-top:1px solid #3a372f;border-bottom:1px solid #3a372f;font-family:Consolas,monospace;font-size:12px;line-height:1.55;color:#e0b59a;">${escapeHtml(d)}</td></tr>
        <tr><td style="padding-top:22px;font-size:16px;line-height:1.55;">
          You asked to receive publication notices. This is the first letter. Every new subscriber gets this same one.
        </td></tr>
        <tr><td style="padding-top:18px;font-family:Consolas,monospace;font-size:11px;letter-spacing:0.16em;color:#c45c32;">WHAT THIS IS</td></tr>
        <tr><td style="padding-top:8px;font-size:15px;line-height:1.6;">
          GENUS//NS is a public registry of invented musical species — music for genres that do not exist yet. Genus is the laboratory. GENUS//NS is the publication layer. Neural Syntax operates it. 0dB_Labs is the label.
        </td></tr>
        <tr><td style="padding-top:12px;font-size:15px;line-height:1.6;">
          Each species has a short id (for example 288FBD), a genome (tuning, rhythm, form), a cover grown from that law, and a master you can listen to on the site.
        </td></tr>
        <tr><td style="padding-top:18px;font-family:Consolas,monospace;font-size:11px;letter-spacing:0.16em;color:#c45c32;">WHAT YOU WILL GET ON SATURDAYS</td></tr>
        <tr><td style="padding-top:8px;font-size:15px;line-height:1.6;">
          Once a week the same agents assemble a short bulletin: which species went public, listen links, and nothing else. No internal tools, no unreleased work, no private correspondence.
        </td></tr>
        <tr><td style="padding-top:22px;">
          <a href="${SITE}" style="font-family:Consolas,monospace;font-size:12px;letter-spacing:0.14em;color:#c45c32;">LISTEN ON GENUSNS.COM</a>
        </td></tr>
        <tr><td style="padding-top:28px;font-family:Consolas,monospace;font-size:11px;line-height:1.5;color:#9a9588;">${escapeHtml(d)}</td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
